### ISSUE TITLE
Dwarf Endgame Not Triggering (3.0.1)

### ISSUE THREAD

**Issue by Hanter-19** [Frodo45127/tww3_dynamic_disasters#2]
The Dwarf endgame does not trigger at the end of the warning timer.

I've attached a zipped save file that is 1 turn before the endgame is supposed to trigger.

[Yvresse-1TurnB4DwarfEndgame2.1353271060598.zip](https://github.com/Frodo45127/tww3_dynamic_disasters/files/11437916/Yvresse-1TurnB4DwarfEndgame2.1353271060598.zip)

Note: I've got 57 mods active in this save (including this mod) and I'm not sure how to share the modlist in case that's helpful. (Let me know if there's some file somewhere that might log all of this that I can share)

I do have a number of mods that add/modify races. In case it helps in debugging (especially if the cause might be incompatibility), these are the race mods that are active in my save:
- Cataph's Kraka Drak
- Cataph's Southern Realms
- Marienburg: The Merchant Empire
- Legendary Characters 3.0
- Mixu's Legendary Lords
- Mixu's Slayer
- Dead Of The Orient
- OvN Lost Factions: Albion
- OvN Lost Factions: Citadel of Dusk
- OvN Lost Factions: Fimir

**Comment by Hanter-19** [comment]
Side note: I got the Raiding Parties Midgame as well (many turns back - unfortunately I no longer have the save) which spawned DE armies around the shores of Ulthuan under Morathi's faction (Cult of Pleasure).

They've just been idling all throughout my game and not doing anything. I can't remember if I eliminated Cult of Pleasure before/during/after the Raiding Parties countdown.

**Comment by Frodo45127** [comment]
The dwaft endgame not working should be fixed now. It was part of kraka drak's patch that was breaking it on some situations.

For armies not moving, as stated in the faq, it's usually caused by the unit caps mods. Not sure what they do, but they end up creating an agent on top of the armies, blocking both from moving. Use a mod or something to remove the agent and the armies will move.

**Comment by Hanter-19** [comment]
Tried the same save file after the recent update, but it seems the event is still not happening.

Here are the script logs if that helps.
[script_log_110523_0054.txt](https://github.com/Frodo45127/tww3_dynamic_disasters/files/11444403/script_log_110523_0054.txt)
[lua_mod_log.txt](https://github.com/Frodo45127/tww3_dynamic_disasters/files/11444404/lua_mod_log.txt)

It says A Grudge Too Far is in progress, and Raiding Parties is ignored because it is in between triggers.

Does the fix only work on a fresh save or before the countdown has triggered?

**Comment by Frodo45127** [comment]
The fix works for any save before the turn the armies should spawn, and it fixed the error on the two campaigns I tested in locally. Can you disable the "Recruit defeated legendary lords" mod and see if that fixes it? No idea why, but the error on your log says that mod is involved somehow in calling the disaster function, which I don't understand why it would be. If it doesn't fix it, at least it should make it easier to read the backtrace.

**Comment by Frodo45127** [comment]
fixed for good this time.

**Comment by Hanter-19** [comment]
Thanks! I've started a new campaign and will help keep an eye out for any script errors
